source 'https://rubygems.org'

gem 'thin'
gem 'rack'
gem 'coffee-script'
gem 'haml'
gem 'sprockets'
gem 'sprockets-helpers'
gem 'sass'
gem 'sprockets-sass'
gem 'compass'
gem 'em-websocket'
gem 'awesome_print'